create table if not exists public.leaderboard_runs (
  id bigint generated by default as identity primary key,
  class_name text not null check (char_length(trim(class_name)) between 1 and 12),
  student_number text not null check (char_length(trim(student_number)) between 1 and 12),
  distance_meters integer not null check (distance_meters >= 0),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_runs_best_idx
  on public.leaderboard_runs (class_name, student_number, distance_meters desc);

create index if not exists leaderboard_runs_distance_idx
  on public.leaderboard_runs (distance_meters desc);

alter table public.leaderboard_runs enable row level security;

drop policy if exists "anon can insert leaderboard runs" on public.leaderboard_runs;
create policy "anon can insert leaderboard runs"
  on public.leaderboard_runs
  for insert
  to anon
  with check (
    char_length(trim(class_name)) between 1 and 12
    and char_length(trim(student_number)) between 1 and 12
    and distance_meters >= 0
  );

drop policy if exists "anon can read leaderboard runs" on public.leaderboard_runs;
create policy "anon can read leaderboard runs"
  on public.leaderboard_runs
  for select
  to anon
  using (true);

drop view if exists public.leaderboard_best;
create view public.leaderboard_best
with (security_invoker = true)
as
select
  class_name,
  student_number,
  max(distance_meters)::integer as distance_meters
from public.leaderboard_runs
group by class_name, student_number;

grant usage on schema public to anon;
grant select, insert on table public.leaderboard_runs to anon;
grant usage, select on sequence public.leaderboard_runs_id_seq to anon;
grant select on table public.leaderboard_best to anon;
